export enum userListType{
    GET_USER_REQUEST='GET_USER_REQUEST',
    GET_USER_SUCCESS = 'GET_USER_SUCCESS',
    GET_USER_FAIL = 'GET_USER_FAIL',
    POST_ADD_USER_REQUEST="POST_ADD_USER_REQUEST",
    POST_ADD_USER_SUCCESS="POST_ADD_USER_SUCCESS",
    POST_ADD_USER_FAİL="POST_ADD_USER_FAİL",
}
